name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital (63)
  pipelines:
    - pipeline: build_pipeline
      source: "Communications-Manager-Build"
      trigger:
        branches:
          include:
            - refs/tags/v*
            - release
            - hotfix

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    hosted_target_connection_path_suffix: ${{ variables.hosted_target_connection_path_suffix }}
    manual_approval_env: manual-approval-ptl
    prod_producer_approval: true
    enable_monitoring: true
    enable_status_monitoring: true
    apigee_deployments:
      - environment: internal-dev
        jinja_templates:
          ENVIRONMENT_TYPE: 'internal'
          ERROR_ABOUT_LINK: ${{ variables.error_about_link }}
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              test_command: 'make internal-dev-test'

      - environment: internal-dev-sandbox
        proxy_path: sandbox
        jinja_templates:
          ENVIRONMENT_TYPE: 'sandbox'
          ERROR_ABOUT_LINK: ${{ variables.error_about_link }}
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              test_command: 'make internal-sandbox-test'
              unit_test_report_name: 'sandbox/sandbox-unit-report.xml'

      - environment: manual-approval
        stage_name: manual_approval_ref
        depends_on:
          - internal_dev
            
      - environment: ref
        depends_on:
          - manual_approval_ref
        jinja_templates:
          ENVIRONMENT_TYPE: 'internal'
          ERROR_ABOUT_LINK: ${{ variables.error_about_link }}
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              test_command: 'make internal-dev-test'

      - environment: manual-approval
        stage_name: manual_approval_internal_qa
        depends_on:
          - internal_dev

      - environment: internal-qa
        depends_on:
          - manual_approval_internal_qa
        jinja_templates:
          ENVIRONMENT_TYPE: 'internal'
          ERROR_ABOUT_LINK: ${{ variables.error_about_link }}
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              test_command: 'make internal-qa-test'

      - environment: manual-approval
        stage_name: manual_approval_internal_qa_sandbox
        depends_on:
          - internal_dev_sandbox

      - environment: internal-qa-sandbox
        proxy_path: sandbox
        depends_on:
          - manual_approval_internal_qa_sandbox
        jinja_templates:
          ENVIRONMENT_TYPE: 'sandbox'
          ERROR_ABOUT_LINK: ${{ variables.error_about_link }}
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              test_command: 'make internal-sandbox-test'
              unit_test_report_name: 'sandbox/sandbox-unit-report.xml'

      - environment: manual-approval
        stage_name: manual_approval_sandbox
        depends_on:
          - internal_qa_sandbox

      - environment: sandbox
        depends_on:
          - manual_approval_sandbox
        proxy_path: sandbox
        jinja_templates:
          ENVIRONMENT_TYPE: 'sandbox'
          ERROR_ABOUT_LINK: ${{ variables.error_about_link }}
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              test_command: 'make prod-sandbox-test'
              unit_test_report_name: 'sandbox/sandbox-unit-report.xml'

      - environment: manual-approval
        stage_name: manual_approval_int
        depends_on:
          - internal_qa

      - environment: int
        depends_on:
          - manual_approval_int
        jinja_templates:
          ENVIRONMENT_TYPE: 'production'
          ERROR_ABOUT_LINK: ${{ variables.error_about_link }}
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              test_command: 'make integration-test'

      - environment: prod
        depends_on:
          - int
          - sandbox
        jinja_templates:
          ENVIRONMENT_TYPE: 'production'
          ERROR_ABOUT_LINK: ${{ variables.error_about_link }}
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              test_command: 'make production-test'
