name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

parameters:
  - name: DISABLE_VERSION_OVERRIDE
    displayName: Disable version override
    type: boolean
    default: false

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

schedules:
  - cron: 0 2 * * *
    displayName: 2am daily
    branches:
      include: ['release']
    always: true

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml
  - name: SERVICE_ARTIFACT_NAME
    value: ''

steps:
# If display version override is not checked, checkout the latest version of release
  - ${{ if eq(parameters.DISABLE_VERSION_OVERRIDE, false) }}:
    - template: ./templates/checkout-latest-release.yml
      parameters:
        environment: 'internal-qa'

# Set up the teams alert webhook
  - template: ./templates/teams-alert-setup.yml
    parameters:
      webhook_uri: 'ALERTS_PROD_API_WEBHOOK_URI'

# Executes the tests
  - template: ./templates/run-tests.yml
    parameters:
      nightly: true
      environment: 'internal-qa'
      test_command: 'make internal-qa-test'

# If the test run did not succeed posts an alert to teams
  - template: ./templates/teams-alert.yml
    parameters:
      title: 'UAT'
      webhook_uri: 'ALERTS_PROD_API_WEBHOOK_URI'