name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/APIM-6679-Python-Update
      endpoint: NHSDigital

schedules:
  - cron: '*/10 * * * *'
    displayName: every 10 minutes
    branches:
      include: ['release']
    always: true

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml
  - name: SERVICE_ARTIFACT_NAME
    value: ''

steps:
# Set up the teams alert webhook
  - template: ./templates/teams-alert-setup.yml
    parameters:
      webhook_uri: 'ALERTS_DEV_API_WEBHOOK_URI'

# Executes the tests
  - bash: |
      make install-python && make mtls-test-dev
    timeoutInMinutes: 2

# If the test run did not succeed posts an alert to teams
  - template: ./templates/teams-alert.yml
    parameters:
      title: 'mTLS Dev'
      webhook_uri: 'ALERTS_DEV_API_WEBHOOK_URI'