variables:
  - group: status-endpoint
  - name: service_name
    value: communications-manager
  - name: short_service_name
    value: cm
  - name: service_base_path
    value: comms
  - name: hosted_target_connection_path_suffix
    value: '{requestpath}'
  - name: error_about_link
    value: 'https://digital.nhs.uk/developer/api-catalogue/nhs-notify'
  - name: python_version
    value: '3.10'
